version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: image
    restart: always
    depends_on:
    - ollama 
    ports:
    - "5000"

  ollama:
    image: ollama/ollama
    ports:
    - "11434:11434"
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always

  nginx:
    image: nginx:1.24.0
    restart: unless-stopped
    depends_on:
    - api
    ports:
    - "80:80"
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
